### ISSUE TITLE
Détails des paramètres d'appel

### ISSUE THREAD

**Issue by pierrejego** [LETG/beachprofile#4]
Nous avons essayé d'utiliser le WPS mais le service sort tout le temps en nullpointer.

BeachProfileTracking

Pour l'utilisation du service beachprofil nous avons besoin de connaître les valeurs des paramètres d'appel.

FeatureCollection -> Nb max de prf ?
interval -> quelle valeur
useSmallestDistance -> quelle valeur
minDist -> quelle valeur
maxDist -> quelle valeur

**Comment by mrouan** [comment]
FeatureCollection : c’est le contenu d’un fichier GeoJson qui contient toutes les coordonnées géographiques. Le fichier doit respecter la structure suivante :
- La FeatureCollection doit contenir un CRS et une liste de Features. Le CRS peut être un système géodésique (WGS84 par exemple) ou une projection cartographique (comme le lambert II). Si le CRS est une projection géographique, il peut y avoir une légère approximation de la distance du profil calculé (cf. page 5).
- Chaque Feature doit avoir une Geometry de type LineString, chaque point doit avoir un x,y,z.
- Chaque Feature doit avoir une propriété Date.
Sélectionnez Text dans la 1ère liste déroulante, puis application/json dans la 2ème liste, puis copiez/collez le contenu de votre GeoJson.
Interval : un intervalle utilisé pour l’interpolation. L’interpolation permet d’avoir des coordonnées aux même distances pour chaque date, utile pour définir des bornes de longueur pour le calcul. Préférez un intervalle à une décimale comme 0.1.
useSmallestDistance : entrez true ou false. Si true : on trouve la longueur du plus petit profil et on utilise cette distance en tant que borne max pour que le volume sédimentaire se fasse sur la même longueur à chaque date. Si false, on se base sur la longueur à la première date et on ignore les dates dont la longueur est plus petite.
Min : la borne minimale de la distance sur lequel se fait le calcul. Entrez 0 pour commencer le calcul à partir du premier point
Max : la borne maximale de la distance sur lequel se fait le calcul. Entrez 0 pour faire le calcul jusqu’au bout du profil
Note : **l’utilisation des bornes min/max nécessite d’avoir défini un intervalle d’interpolation pour avoir une coordonnée aux bornes demandées. Par exemple pour borne min à 4,5 mètres il faut un point à 4,5metres pile pour chaque date donc un intervalle de 0.5 ou 0.1**

**Comment by pierrejego** [comment]
Appel fonctionnel avec paramètres 
```
Interval -> 0.1
useSmallesDistance -> true
minDist-> 0
maxDist -> 0
```

réponse sur avec PRF1 VOUGOT

```
date;volume;diffWithPrevious;previousEvolutionPercent;totalEvolutionPercent;
2022-03-03Z;1.7675996120229183;0.1304472001078123;7.967932561343995;15.428384601127568;
2011-06-16Z;1.637152411915106;0.11365946093719081;7.460452039783573;7.460452039783573;
2004-12-08Z;1.5234929509779152;0.0;0.0;0.0;
```
